import { useEffect, useMemo, useState } from "react";

import styles from "./KickFromCsvPanel.module.css";
import type {
  CsvFileMetadata,
  KickFromCsvFileResult,
  KickFromCsvResponse,
} from "../../models/types";
import { deleteCsvFile, fetchCsvFiles } from "../../services/csv/csvFiles";
import { kickFromCsv } from "../../services/csv/kickFromCsv";
import { cancelKickJob } from "../../services/csv/cancelKick";
import { CsvDownloadButton } from "../shared/CsvDownloadButton";
import { ConfirmationModal } from "../shared/ConfirmationModal";

const CSV_LIST_PAGE_SIZE = 10;

export const KickFromCsvPanel = () => {
  const [files, setFiles] = useState<CsvFileMetadata[]>([]);
  const [selectedMap, setSelectedMap] = useState<Record<string, boolean>>({});
  const [filePage, setFilePage] = useState(1);
  const [dryRun, setDryRun] = useState(true);
  const [kicking, setKicking] = useState(false);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [results, setResults] = useState<KickFromCsvFileResult[] | null>(null);
  const [cancelling, setCancelling] = useState(false);
  const [deletingFilename, setDeletingFilename] = useState<string | null>(null);
  const [deleteCandidateFilename, setDeleteCandidateFilename] = useState<
    string | null
  >(null);

  const selectedFilenames = useMemo(
    () =>
      files
        .filter((file) => selectedMap[file.filename])
        .map((file) => file.filename),
    [files, selectedMap]
  );
  const totalFilePages = Math.max(
    1,
    Math.ceil(files.length / CSV_LIST_PAGE_SIZE),
  );
  const visibleFiles = useMemo(() => {
    const startIndex = (filePage - 1) * CSV_LIST_PAGE_SIZE;
    return files.slice(startIndex, startIndex + CSV_LIST_PAGE_SIZE);
  }, [filePage, files]);
  const fileStart =
    files.length === 0 ? 0 : (filePage - 1) * CSV_LIST_PAGE_SIZE + 1;
  const fileEnd = Math.min(files.length, filePage * CSV_LIST_PAGE_SIZE);

  useEffect(() => {
    void refresh();
  }, []);

  useEffect(() => {
    setFilePage((current) => Math.min(current, totalFilePages));
  }, [totalFilePages]);

  const refresh = async () => {
    try {
      const fetched = await fetchCsvFiles();
      setFiles(fetched);
      setSelectedMap((prev) => {
        const next: Record<string, boolean> = {};
        fetched.forEach((file) => {
          if (prev[file.filename]) {
            next[file.filename] = true;
          }
        });
        return next;
      });
    } catch (error) {
      setErrorMessage((error as Error).message);
    }
  };

  const toggleSelection = (filename: string) => {
    setSelectedMap((prev) => ({
      ...prev,
      [filename]: !prev[filename],
    }));
  };

  const handleDelete = async () => {
    const filename = deleteCandidateFilename;
    if (!filename || kicking || deletingFilename) {
      return;
    }

    setDeletingFilename(filename);
    setStatusMessage(null);
    setErrorMessage(null);
    try {
      await deleteCsvFile(filename);
      setSelectedMap((prev) => {
        const next = { ...prev };
        delete next[filename];
        return next;
      });
      await refresh();
      setStatusMessage("CSV export deleted.");
      setDeleteCandidateFilename(null);
    } catch (error) {
      setErrorMessage((error as Error).message);
    } finally {
      setDeletingFilename(null);
    }
  };

  const handleKick = async () => {
    if (selectedFilenames.length === 0 || kicking) {
      setErrorMessage("Select at least one CSV file to continue.");
      return;
    }

    setKicking(true);
    setErrorMessage(null);
    setStatusMessage(null);
    setResults(null);

    try {
      const response: KickFromCsvResponse = await kickFromCsv({
        filenames: selectedFilenames,
        dryRun,
      });
      setStatusMessage(response.message);
      setResults(response.results);
      await refresh();
    } catch (error) {
      const message = (error as Error).message;
      if (message.toLowerCase().includes("cancel")) {
        setStatusMessage(message);
        setErrorMessage(null);
      } else {
        setErrorMessage(message);
      }
      setResults(null);
    } finally {
      setKicking(false);
      setCancelling(false);
    }
  };

  const handleCancel = async () => {
    if (!kicking || cancelling) {
      return;
    }
    setCancelling(true);
    try {
      await cancelKickJob();
      setStatusMessage("Kick cancellation requested.");
      setErrorMessage(null);
    } catch (error) {
      setErrorMessage((error as Error).message);
    } finally {
      setCancelling(false);
    }
  };

  return (
    <section className={styles.panel}>
      <div className={styles.header}>
        <div>
          <h2>Kick from CSV</h2>
          <p>
            Select one or more CSV exports generated by the scanner and remove
            the matching members from the guild.
          </p>
        </div>
        <button
          type="button"
          className="secondary-button"
          onClick={refresh}
          disabled={kicking}
        >
          Refresh list
        </button>
      </div>

      <div className={styles.content}>
        <div className={styles.csvList}>
          {files.length === 0 ? (
            <p className={styles.empty}>
              No CSV exports found in the csv/ directory.
            </p>
          ) : (
            <>
              <ul>
                {visibleFiles.map((file) => (
                  <li key={file.filename} className={styles.csvItem}>
                    <label>
                      <input
                        type="checkbox"
                        checked={Boolean(selectedMap[file.filename])}
                        onChange={() => toggleSelection(file.filename)}
                        disabled={kicking}
                      />
                      <span>
                        <strong>{file.filename}</strong>
                        <small>{formatCsvFileDetail(file)}</small>
                      </span>
                    </label>
                    <CsvDownloadButton
                      className={styles.downloadLink}
                      filename={file.filename}
                      label="Download"
                      size="compact"
                    />
                    <button
                      type="button"
                      aria-label={`Delete ${file.filename}`}
                      className={`${styles.deleteButton} secondary-button secondary-button--danger`}
                      disabled={kicking || deletingFilename === file.filename}
                      onClick={() => setDeleteCandidateFilename(file.filename)}
                    >
                      Delete
                    </button>
                  </li>
                ))}
              </ul>
              {files.length > CSV_LIST_PAGE_SIZE && (
                <div className={styles.listPagination}>
                  <span className={styles.pageCount}>
                    {fileStart}-{fileEnd} of {files.length}
                  </span>
                  <button
                    type="button"
                    aria-label="Previous CSV export page"
                    className="secondary-button"
                    disabled={filePage <= 1}
                    onClick={() =>
                      setFilePage((current) => Math.max(1, current - 1))
                    }
                  >
                    Previous
                  </button>
                  <button
                    type="button"
                    aria-label="Next CSV export page"
                    className="secondary-button"
                    disabled={filePage >= totalFilePages}
                    onClick={() =>
                      setFilePage((current) =>
                        Math.min(totalFilePages, current + 1),
                      )
                    }
                  >
                    Next
                  </button>
                </div>
              )}
            </>
          )}
        </div>

        <div className={styles.actions}>
          <label className={styles.dryRunToggle}>
            <input
              type="checkbox"
              checked={dryRun}
              onChange={(event) => setDryRun(event.target.checked)}
              disabled={kicking}
            />
            <span>Dry run (report only, no kicks)</span>
          </label>
          <button
            type="button"
            disabled={kicking || selectedFilenames.length === 0}
            onClick={handleKick}
            className={styles.kickButton}
          >
            {kicking
              ? "Processing…"
              : dryRun
              ? "Dry run selected CSVs"
              : "Kick selected users"}
          </button>
          {kicking && (
            <button
              type="button"
              className="secondary-button secondary-button--danger"
              onClick={handleCancel}
              disabled={cancelling}
            >
              {cancelling ? "Cancelling…" : "Cancel kick job"}
            </button>
          )}
          <p className={styles.hint}>
            {selectedFilenames.length === 0
              ? "Select at least one CSV."
              : `${selectedFilenames.length} file${
                  selectedFilenames.length === 1 ? "" : "s"
                } selected.`}
          </p>
        </div>
      </div>

      <div className="feedback">
        {statusMessage && <p className="status success">{statusMessage}</p>}
        {errorMessage && <p className="status error">{errorMessage}</p>}
      </div>

      {results && results.length > 0 && (
        <div className={styles.results}>
          {results.map((file) => (
            <article key={file.filename} className={styles.resultCard}>
              <header>
                <h3>{file.filename}</h3>
                <span className={styles.badge}>
                  {file.dryRun ? "Dry run" : "Live kick"}
                </span>
              </header>
              <ul>
                <li>
                  Total rows: <strong>{file.totalRows}</strong>
                </li>
                <li>
                  Matched members: <strong>{file.matchedUsers}</strong>
                </li>
                <li>
                  Successful kicks: <strong>{file.successfulKicks}</strong>
                </li>
              </ul>
              {file.failures.length > 0 && (
                <details>
                  <summary>{file.failures.length} issue(s) encountered</summary>
                  <ul>
                    {file.failures.map((failure, index) => (
                      <li key={`${file.filename}-failure-${index}`}>
                        {failure}
                      </li>
                    ))}
                  </ul>
                </details>
              )}
            </article>
          ))}
        </div>
      )}
      <ConfirmationModal
        confirmLabel="Delete CSV"
        confirmingLabel="Deleting..."
        isConfirming={Boolean(deletingFilename)}
        isOpen={Boolean(deleteCandidateFilename)}
        message={`Are you sure you want to delete ${deleteCandidateFilename ?? "this CSV export"}?`}
        onCancel={() => {
          if (!deletingFilename) {
            setDeleteCandidateFilename(null);
          }
        }}
        onConfirm={() => void handleDelete()}
        title="Delete CSV export"
      />
    </section>
  );
};

const formatCsvFileDetail = (file: CsvFileMetadata): string => {
  const modifiedAt = new Date(file.modifiedAt).toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
  const size = formatBytes(file.size);
  const rowDetail =
    typeof file.rowCount === "number" ? `${file.rowCount} users` : size;

  return `${rowDetail} · ${modifiedAt}`;
};

const formatBytes = (size: number): string => {
  if (!Number.isFinite(size) || size < 0) {
    return "Unknown size";
  }

  if (size < 1024) {
    return `${size} B`;
  }

  const kilobytes = size / 1024;
  if (kilobytes < 1024) {
    return `${kilobytes.toFixed(1)} KB`;
  }

  return `${(kilobytes / 1024).toFixed(1)} MB`;
};
